-- Inventory Service Seed Data

INSERT INTO inventory (product_id, quantity, reserved_quantity, warehouse_location, reorder_level, last_restocked, created_at, updated_at) VALUES
(1, 50, 5, 'Warehouse A - Sector 1', 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, 200, 10, 'Warehouse B - Sector 2', 50, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(3, 75, 8, 'Warehouse A - Sector 1', 15, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(4, 30, 3, 'Warehouse C - Sector 3', 5, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(5, 150, 12, 'Warehouse B - Sector 2', 30, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(6, 100, 5, 'Warehouse A - Sector 1', 20, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(7, 80, 7, 'Warehouse B - Sector 2', 15, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(8, 40, 4, 'Warehouse C - Sector 3', 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(9, 300, 25, 'Warehouse B - Sector 2', 75, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(10, 60, 6, 'Warehouse A - Sector 1', 12, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

